### ISSUE TITLE
Not clear how to configure service checks

### ISSUE THREAD

**Issue by LarsFronius** [saltstack-formulas/sensu-formula#18]
I really don't see a good example of this being done in e.g. the pillar.example.

I noticed check_cron is being configured for me, however I don't see how I could extend this to more service checks. Is this implemented already? If so, do you have any guidance for me?

**Comment by powellchristoph** [comment]
Currently it only copies over the actual check scripts. There isn't a method of configuring the actual checks. That being said, we have implemented a method of defining the checks in the pillar but it hasn't been included here yet. I'll look into getting it cleaned up and merged.

**Comment by envintus** [comment]
Hi @powellchristoph, would this work cover defining what a check looks like using pillar data or would it allow you to build a list of checks from pillar data to then apply to a sensu client? Currently I'm trying to figure out how to build a list dynamically using pillar data, so that only certain checks are distributed to certain systems. E.g. MySQL nodes only receive the MySQL checks.

**Comment by powellchristoph** [comment]
@envintus yes, the method that we have implemented lets you build your list of checks which are defined in the pillar and then apply them to specific clients. We are discussing how to contribute it back at the moment. We are currently using a strict naming convention to target checks for the clients but I think we can tweek it to support other methods. Give me alittle time.

**Comment by envintus** [comment]
Sounds awesome. Looking forward to this and potentially a feature branch to help with it.

**Comment by powellchristoph** [comment]
@envintus @LarsFronius Take a look at #23 and see if it meets your needs.

**Comment by envintus** [comment]
This looks like it will handle quite a bit of my needs with checks. Corresponding client side scripts or gems I guess will still require me to write my own state and distribute them. I know there is an option to install additional gems for clients, but I'll likely have homegrown scripts that are not hosted gems or even gems for that matter.

**Comment by envintus** [comment]
Actually the ``sensu-install`` utility has a optional flag to provide an alternate source for installing gems. This should satisfy most use cases.

``-s, --source SOURCE Install Sensu plugins from a custom SOURCE``
