### ISSUE TITLE
last commit issues

### ISSUE THREAD

**Issue by kmkramer** [saltstack-formulas/sensu-formula#27]
client.sls has code diffs in it
lines 39,46,48,117 and 134

and are we missing a keepalive in the pillar_map.jinja file. I'm getting
Rendering SLS 'base:sensu.client' failed: Jinja variable 'dict object' has no attribute 'keepalive'

**Comment by kmkramer** [comment]
I managed to remove the lines above and replace the keepalive line with the following to work around the problem

{% if sensu.client.keepalive is defined %}
          keepalive: {{ sensu.client.keepalive }}
{% endif %}

Is this the client->server keepalive threshold if you want to override the defaults? https://sensuapp.org/docs/0.16/keepalives

**Comment by powellchristoph** [comment]
looks like someone merged it with the diff in without resolving the conflicts.
```
<<<<<<< HEAD
{% if sensu.client.get("command_tokens") %}
          command_tokens: {{ sensu.client.command_tokens }}
{% endif %}
{% if sensu.client.get("redact") %}
          redact: {{ sensu.client.redact }}
{% endif %}
=======
          keepalive: {{ sensu.client.keepalive }}
>>>>>>> 3e357cda916c4c084e832efa3c51cb1b09ca36aa
```
