### ISSUE TITLE
current state

### ISSUE THREAD

**Issue by x70b1** [saltstack-formulas/sensu-formula#52]
Hi guys

the Sensu Community would like to participate more strongly in the development of the intersection between Sensu and SaltStack. It is very clear that a up-to-date formular is an important step in this direction.

We are currently in the process of looking for a good place to push development forward and which formulars and states already exist.

We can't see if this repository is up to date. There are some open pull requests and issues. Can you give us a statement here?

**Comment by UtahDave** [comment]
Hi @x70b1.  The formulas in this saltstack-formulas github organization are largely community driven. Some get more attention than others. 

We'd love to help from the Sensu Community to improve both this sensu-formula and any Salt States and modules.  If you or someone else from the Sensu Community would like to get more involved and help test and merge pull requests on this sensu-formula repo, we'd be more than happy to give him or her admin rights on this repo.  I can help coordinate that.

**Comment by x70b1** [comment]
Hi @UtahDave 
Thank you for your response.

Yeah, it seems there's not much feedback here. I'd take this job. Within the Sensu community we can then work on it and take further steps.

**Comment by EvaSDK** [comment]
Whatever you do, please submit PR here as this is the place where community can review stuff. Most contribs I did to formulas are really slow to get in. There are several reasons for that (in order from my POV):
* few contributors actually having time to review
* few contributors getting actual write access to the formula you are interested in
* small incentive to get back to a formula once you got your setup in place
but it's still better to work here than fork and fragment user base.
